version: '3.5'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./app/:/usr/src/app
  db:
    image: postgres
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: django
